### PR TITLE
Prepare data architecture documentation

### PR DESCRIPTION
**Pull request by trekab**
Adds ERD for 'Stay in Touch' app

### CODE REVIEW

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :warning: 
Hi there @trekab, how are you? :smile: 
Please let me ask you, are you without a partner?

Nice job in the ERD :+1: 
We only need to fix a minor thing

- [x] Since Friend table uses 2 foreign keys from the User table, the User table needs to have 2 Cardinality One (and only one) to many. On your ERD you already have one arrow linking the User table to Friend table. You only need to add more one.

Please kindly submit for code review again after making this change.

**Sergio Torres**

**Comment by trekab** [comment]
I am currently working without a coding partner since we were unpaired last week.

**Review by Redvanisation — APPROVED** [review]
# Milestone approved ✔️ 

### Hello team 🌟 

### _Nice work on this milestone, it seems that you have met the requirements. 👍_ 

### You may merge it and submit a project completion form. 🚀 

### Good luck! 🍀

**Comment by trekab** [comment]
:ok_hand:

**Pull request merged**
