### PR TITLE
Implement friendships with 2 rows for mutual friendship

### PR DESCRIPTION
**Pull request by trekab**
Adds 2 rows for mutual friendships.

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required 
Great work implementing two rows for mutual friendship.
Let's make some changes in order to make our application more efficient.

### [REQUIRED]
**User Model**
* We can define pal/friends method using SQL query instead of passing objects to the application memory
Instead of having this 
```ruby
def pals
    pals_array = friends.map { |friend| friend.pal if friend.accepted? }
    inverse_pals = inverse_friends.map { |friend| friend.user if friend.accepted? }
    inverse_pals.each { |pal| pals_array << pal }
    pals_array.compact
end
```
We can have
```ruby
has_many :pals, -> { where friendship_status: "accepted" }, class_name: "Friend"
```
We can also change :point_down: 
```ruby
def pending_friends
    friends.map { |friend| friend.pal if friend.pending? }.compact
end
```
to:
```ruby
has_many :pending_friendships, -> { where friendship_status: "pending" }, class_name: "Friend", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :pal
```
And lastly we can change this:
```ruby
def friend_requests
    inverse_friends.map { |friend| friend.user unless friend.accepted? }.compact
end
```
to:
```ruby
has_many :inverted_friendships, -> { where friendship_status: "pending" }, class_name: "Friend", foreign_key: "pal_id"
has_many :friend_requests, through: :inverted_friendships, source: :user
```
* We forgot to add unit and integration tests using capybra and rspec ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)  from  Pathwright)

**After implementing the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by trekab** [comment]
:+1:  Thanks, @wathigo!

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,
Thanks for the improvements. However, there is a requirement that is not met.
I created two user and make them to be friend but here is what I got from the console
```ruby
2.7.0 :001 > Friend.all
Friend Load (0.6ms)  SELECT  "friends".* FROM "friends" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friend id: 1, user_id: 7, pal_id: 6, friendship_status: "accepted", created_at: "2020-03-27 17:50:19", updated_at: "2020-03-27 17:53:19">]> 
2.7.0 :002 > 
```
It was asked that when friendship is confirmed, an additional row with reversed user-friend pair is created.

Please, Kindly fix that and submit a new code review request.
Thanks

Mael FOSSO

**Comment by trekab** [comment]
Hey @maelfosso, thanks for the timely review. I don't seem to be getting the same output you are getting. Could you please elaborate more on how you are accepting the friendships?

**Comment by trekab** [comment]
Hey @maelfosso <https://github.com/maelfosso>, thanks for the timely
review. I don't seem to be getting the same output you are getting. Could
you please elaborate more on how you are accepting the friendships?

**Review by wathigo — APPROVED** [review]
### Approved :heavy_check_mark: 
Great work implementing the suggested changes :+1: 
Two rows have been created upon friendship confirmation
```ruby
Friend.all
  Friend Load (0.6ms)  SELECT  "friends".* FROM "friends" LIMIT $1  [["LIMIT", 11]]
=> #<ActiveRecord::Relation [#<Friend id: 8, user_id: 1, pal_id: 2, friendship_status: "accepted", created_at: "2020-03-27 23:10:11", updated_at: "2020-03-27 23:10:40">, #<Friend id: 9, user_id: 2, pal_id: 1, friendship_status: "accepted", created_at: "2020-03-27 23:10:40", updated_at: "2020-03-27 23:10:40">]>
```

**You may proceed to the next milestone.**

**Good luck :four_leaf_clover: 
Simon Wathigo**

**Comment by trekab** [comment]
:+1: Thanks @wathigo.

**Pull request merged**
