### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by trekab**
Adds model with associations and all requested features for friendships.

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello, thank you for good job.
However, there are some changes to do

1. As required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png), Posts timeline includes posts written by logged-in user and their friends, which is not the case in your app.

2. There are some missing features
- User should be able to invite friends [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png)
- User should be able to see friendships request [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png)
- User should be able to accept/reject friendship request [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png)
- and many others

Kindly make the suggested changes and submit a new code review request.
Thanks.

Mael FOSSO

**Comment by trekab** [comment]
I have added the required friendship functionality. A user is now able to see friend requests, accept them or reject them and also make friend requests from the users' index page and show page.

**Comment by samgaco** [comment]
Hi @trekab :high_brightness: 

- [x] I can see the following requirement is not yet well implemented:


> 1. As required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png), Posts timeline includes posts written by logged-in user and their friends, which is not the case in your app.

Please, have into account this: If I create an User A, and I post something, and then I create an User B and I log into the application, User B should not be able to see posts made by User A unless they are friends, right now User B is able to see User A posts even if they are not friends.



- [x] **[SUGGESTION]**  And as for this other requirement:


[User should be able to see friendships request [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png)
](url)

I would suggest making it more visible (to show some kind of notification in the navigation bar)

Please, work on those and submit back for another review once you are done :+1: 

----------------------

* ###### STATUS OF THE MILESTONE: REQUESTED CHANGES :stop_sign:

**Comment by trekab** [comment]
Thanks for the descriptive/actionable feedback, @samgaco. Let me work on the required changes and re-submit for another code review.

**Review by Ispirett — APPROVED** [review]
# Status Approved :+1: 
Great work folks !!! with changes made  :100:

**Comment by trekab** [comment]
Thanks, @Ispirett. I appreciate the timely review.

**Pull request merged**
